Add `org_name` config param
opentelekomcloud-infra/vault-plugin-secrets-github pull request #3
Opened 2021-11-23 11:10 UTC by lego963

Add `org_name` config param as alternative of `ins_id`

2021-11-25 12:46 UTC, outcatcher requested changes

2021-11-25 12:46 UTC, outcatcher commented on github/integration_test.go
> +//go:build integration
This seems to be a redundant change

2021-11-25 12:46 UTC, outcatcher commented on github/backend_test.go
> +	"github.com/hashicorp/go-hclog"
This seems to be a redundant change

2021-11-25 12:46 UTC, outcatcher commented on github/client.go
> +			instID = v.ID
You can return from here and make replace code after the cycle with just
```go
return 0, fmt.Errorf("installation ID for the organization wasn't found")
```

Maybe also reword error message? Mentioning app not installed in the organization.

2021-11-25 12:46 UTC, outcatcher commented on github/path_config_test.go
> +	t.Run("Exist Organization", func(t *testing.T) {
You can use sub-tests for those two `Exist` tests, it seems only configuration differs, but not the logic.

2021-11-25 12:46 UTC, outcatcher commented on github/path_config_test.go
> +	t.Run("FailedStoragePersist Organization", func(t *testing.T) {
You can use sub-tests for those two `FailedStoragePersist` tests, it seems only configuration differs, but not the logic.

2021-11-25 13:02 UTC, lego963 commented on github/backend_test.go
> +	"github.com/hashicorp/go-hclog"
this is redundant alias

2021-11-26 10:32 UTC, outcatcher approved these changes

2021-11-26 11:43 UTC, merged